export const ADD_TO_CART_COUNT = 'ADD_TO_CART_COUNT';
export const ADD_TO_CART_LIST = 'ADD_TO_CART_LIST';
export const ADD_TO_TOTAL_AMOUNT = 'ADD_TO_TOTAL_AMOUNT';


export const DELETE_FROM_CART_COUNT = 'DELETE_FROM_CART_COUNT';
export const DELETE_FROM_CART_LIST = 'DELETE_FROM_CART_LIST';
export const DELETE_FROM_TOTAL_AMOUNT = 'DELETE_FROM_TOTAL_AMOUNT';